### Obteniendo datos
GET http://localhost:3001/api/users

### Creando datos
POST http://localhost:3001/api/users

{
    "nombre": "Carlos",
    "apellido": "Perez"
}

### Actualizando datos
PUT http://localhost:3001/api/users

### Eliminando datos
DELETE http://localhost:3001/api/users

